### ISSUE TITLE
ace-editorで日本語入力を行った場合、日本語文字が豆腐になる

### ISSUE THREAD

**Issue by tkhr-sait** [scenario-test-framework/scenario-test#1]
### 事象
docker環境のace-editorで日本語入力を行った場合、日本語文字が豆腐になる
※windows環境では問題なし

### バージョン
0.0.1

### 実行環境
debian stretch

### ログ
```
なし
```

### 再現手順
1. ace-editorに日本語を入力する

### 想定原因
1. windows環境では発生しないことから、フォント関連のインストールが足りていないと思われる

**Comment by suwa-sh** [comment]
最近は web界隈だと no more tofu フォントが多いみたいですー
https://qiita.com/dd511805/items/dfe03c5486bf1421875a

**Comment by tkhr-sait** [comment]
ありがとうございます！
alpineはtofuフォントで対応しておきました
